# Generated by Django 5.2.6 on 2025-09-16 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Football Shoes'), ('ball', 'Football'), ('accessories', 'Accessories'), ('equipment', 'Training Equipment'), ('fan_merch', 'Fan Merchandise')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('size', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('released', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
