# Generated by Django 5.2.6 on 2025-09-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='released',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
